### ISSUE TITLE
[Request]Can you add a blacklist feature?

### ISSUE THREAD

**Issue by sweetymajo** [Tslat/TslatEntityStatus#27]
As the title, I would like to not display the health of some entities because some entities are more like a boss's attack method and there is no need to display their health. Therefore, I hope to add this feature.

**Comment by Tslat** [comment]
You have _live_ entities, with health, as a bosses' attack?

That sounds.. super dodgy

**Comment by norfaremc** [comment]
This is a thing! Actually some of the mobs in my modpack have abilities that are technically rendered in as entities that you cannot attack, and the abilities end up having health bars because they are entities. I have no clue how you’d fix that as they’re technically hostile entities and you’d probably have to go in and make specific compatibilities with every mod that has entity abilities, which is definitely way too much work. For now I just deal with it lol.

**Comment by Tslat** [comment]
I mean sure, but that's just lazy coding lol
Non-living entities don't have health, and can be used just fine

**Comment by norfaremc** [comment]
I think some mod creators can be a little stinky and lazy sometimes, yeah. Nonetheless, I'm grateful for the mods :) 

But a blacklist feature would actually be really nice.

**Comment by Tslat** [comment]
👍

**Comment by Tslat** [comment]
Done in 1.5
