### ISSUE TITLE
I can't read the numbers.

### ISSUE THREAD

**Issue by YOMA8338** [Tslat/TslatEntityStatus#63]
![image](https://github.com/user-attachments/assets/f54e2712-5637-4acc-9104-2f9ce727b383)
![image](https://github.com/user-attachments/assets/f752a1db-c7a5-49fc-ac2f-1551e4ab4362)
Look at the upper left.
If the inventory is not open it is very small and not in the correct position.
I have not tried it with TslatEntityStatus only, so if it is not a problem on the TES side, I will send you a mod list.

**Comment by YOMA8338** [comment]
I am using Fabric 1.21.4-0.16.9,
Fabric1.21.3-0.16.9 also produces exactly the same situation.

**Comment by Tslat** [comment]
That shouldn't be rendering anyway

It looks like some mod is forcing it to render when it shouldn't, which is not TES

**Comment by mysticdrew** [comment]
@Tslat, Yoma just reached out to me because they noticed journeymap waypoint icons are the issue. 

Your hud mixin is right before`gui.render` call in `GameRenderer.class`. 
My hud mixin is right at the invoke `gui.render` in the`Gui.class`. 

If I move my mixin right before yours in `GameRenderer`, issue is solved. If I put it right after, issue occurs. 

Interestingly, if I run a `buffers.endBatch();` right at the beginning of this mixin when it is right after your mixin, it fixes the issue. 
Works:
```
        var minecraft = Minecraft.getInstance();
        var buffers = minecraft.renderBuffers().bufferSource();
        buffers.endBatch();
        HudOverlayHandler.getInstance().renderWaypointDecos(new GuiGraphics(minecraft, buffers));
```

Does not work:
```
        var minecraft = Minecraft.getInstance();
        var buffers = minecraft.renderBuffers().bufferSource();
        HudOverlayHandler.getInstance().renderWaypointDecos(new GuiGraphics(minecraft, buffers));
```

This leads me to believe you are missing an endBatch or endLastBatch somewhere in your hud rendering code. Because my setProjectionMatrix call is modifying the text of your hud.

**Comment by Tslat** [comment]
Thanks for the info

I'll take a look when I get the chance
